### ISSUE TITLE
after login getting err

### ISSUE THREAD

**Issue by Keyz400** [Zain-ul-din/whatsapp-ai-bot#41]
✔ QR has been generated! | Scan QR Code with you're mobile.
⠋ loading chat...
/root/whatsapp-ai-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
    at __puppeteer_evaluation_script__:5:95
    at ExecutionContext._evaluateInternal (/root/whatsapp-ai-bot/node_modules/puppeteer/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ExecutionContext.evaluate (/root/whatsapp-ai-bot/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
    at Client.initialize (/root/whatsapp-ai-bot/node_modules/whatsapp-web.js/src/Client.js:323:9)

Node.js v18.17.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@thunder:~/whatsapp-ai-bot#

**Comment by Zain-ul-din** [comment]
[Track this here](https://github.com/Zain-ul-din/whatsapp-ai-bot/issues/40)
